import Head from 'next/head'
import style from 'styles/Home.module.css'
import Example from 'pages/example/index';

export default function Home() {
  return (
    <div>
      <Head>
        <title>React SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <Example/>
      </main>
    </div>
  )
}
